# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba3a088007fcf993231db8a4b778532dec7363bc1339dafe024413363df8d2eeeea6f295c4e140d852aef0a7afabe572e31876a609655ede0376fc4c8c7e4992

test:
  secret_key_base: 7a0d32845dfb4799194905e5bfa77948164d11d4929ddf6999f4cde7416883c8c2c9fe4f6961bef3301ef50cf9a947853c9f9b1423a2a0d7a59094a08f215be3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
